### EQUITY SECTORS (GICS) ###
"10":
  name: Energy Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"15":
  name: Materials Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"20":
  name: Industrials Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"25":
  name: Consumer Discretionary Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"30":
  name: Consumer Staples Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"35":
  name: Health Care Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"40":
  name: Financials Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"45":
  name: Information Technology Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"50":
  name: Communication Services Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"55":
  name: Utilities Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
"60":
  name: Real Estate Sector
  asset_class: US equity sector
  exchange_name: Chicago Mercantile Exchange (CME)
### COMMODITY FUTURES ###
ZW:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-WHEAT COMPOSITE FUTURES CONT.
  name: Chicago Wheat
  asset_class: commodity
  curcdd: USD
  ric: W
KE:
  exchange_name: Kansas City Board of Trade
  calcseriesname: KCBT-HRW WHEAT COMP CONTINUOUS
  name: Kansas Wheat
  asset_class: commodity
  curcdd: USD
  ric: KW
ZC:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-CORN COMP. CONTINUOUS
  name: Corn
  asset_class: commodity
  curcdd: USD
  ric: C
ZS:
  exchange_name: eCBOT
  calcseriesname: CBT-SOYBEANS COMP. CONT.
  name: Soybeans
  asset_class: commodity
  curcdd: USD
  ric: S
KC:
  exchange_name: New York Board of Trade (NYBOT)
  calcseriesname: CSCE-COFFEE 'C' CONTINUOUS
  name: Coffee
  asset_class: commodity
  curcdd: USD
  ric: KC
SB:
  exchange_name: New York Board of Trade (NYBOT)
  calcseriesname: "CSCE-SUGAR #11 CONTINUOUS"
  name: Sugar
  asset_class: commodity
  curcdd: USD
  ric: SB
CC:
  exchange_name: New York Board of Trade (NYBOT)
  calcseriesname: CSCE-COCOA CONTINUOUS
  name: Cocoa
  asset_class: commodity
  curcdd: USD
  ric: CC
CT:
  exchange_name: New York Board of Trade (NYBOT)
  calcseriesname: "CSCE-COTTON #2 CONTINUOUS"
  name: Cotton
  asset_class: commodity
  curcdd: USD
  ric: CT
HE:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-LEAN HOGS COMP. CONTINUOUS
  name: Lean Hogs
  asset_class: commodity
  curcdd: USD
  ric: LH
LE:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-LIVE CATTLE COMP. CONTINUOUS
  name: Live Cattle
  asset_class: commodity
  curcdd: USD
  ric: LC
GF:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-FEEDER CATTLE COMP. CONTINUOUS
  name: Feeder Cattle
  asset_class: commodity
  curcdd: USD
  ric: FC
CL:
  exchange_name: New York Mercantile Exchange
  calcseriesname: NYM-LIGHT CRUDE OIL CONTINUOUS
  name: WTI Crude Oil
  asset_class: commodity
  curcdd: USD
  ric: CL
HO:
  exchange_name: New York Mercantile Exchange
  calcseriesname: NYM-NY HARBOR ULSD CONTINUOUS
  name: Heating Oil
  asset_class: commodity
  curcdd: USD
  ric: HO
RB:
  exchange_name: New York Mercantile Exchange
  calcseriesname: NYMEX-RBOB GASOLINE CONTINUOUS
  name: RBOB Gasoline (replaces NY Harbor Unleaded Gasoline, pre-2006)
  asset_class: commodity
  curcdd: USD
  ric: RB
G:
  exchange_name: ICE Futures Europe
  calcseriesname: ICE-GAS OIL CONTINUOUS
  name: ICE Gas Oil
  asset_class: commodity
  curcdd: USD
  ric: LGO
BRN:
  exchange_name: ICE Futures Europe
  calcseriesname: ICE-BRENT CRUDE OIL CONTINUOUS
  name: Brent Crude Oil
  asset_class: commodity
  curcdd: USD
  ric: LCO
NG:
  exchange_name: New York Mercantile Exchange
  calcseriesname: NYM-NATURAL GAS CONTINUOUS
  name: Natural Gas
  asset_class: commodity
  curcdd: USD
  ric: NG
AHD:
  exchange_name: London Metal Exchange
  calcseriesname: LME-ALUMINIUM CONTINUOUS
  name: LME Aluminium
  asset_class: commodity
  curcdd: USD
  ric: CMAL
CAD:
  exchange_name: London Metal Exchange
  calcseriesname: LME-COPPER CONTINUOUS
  name: LME Copper
  asset_class: commodity
  curcdd: USD
  ric: CMCU
NID:
  exchange_name: London Metal Exchange
  calcseriesname: LME-NICKEL CONTINUOUS
  name: LME Nickel
  asset_class: commodity
  curcdd: USD
  ric: CMNI
PBD:
  exchange_name: London Metal Exchange
  calcseriesname: LME-LEAD CONTINUOUS
  name: LME Lead
  asset_class: commodity
  curcdd: USD
  ric: CMPB
ZSD:
  exchange_name: London Metal Exchange
  calcseriesname: LME-ZINC CONTINUOUS
  name: LME Zinc
  asset_class: commodity
  curcdd: USD
  ric: CMZN
GC:
  exchange_name: Commodities Exchange Center
  calcseriesname: CMX-GOLD 100 OZ CONTINUOUS
  name: Gold
  asset_class: commodity
  curcdd: USD
  ric: GC
SI:
  exchange_name: Commodities Exchange Center
  calcseriesname: CMX-SILVER 5000 OZ CONT.TRADITIONAL
  name: Silver
  asset_class: commodity
  curcdd: USD
  ric: SI
HG:
  exchange_name: Commodities Exchange Center
  calcseriesname: CMX-HIGH GRADE COPPER CONT.TRAD
  name: Copper (High Grade)
  asset_class: commodity
  curcdd: USD
  ric: HG
### BONDS FUTURES ###
ZB:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-30 YR US T-BOND COMP CONTINUOUS
  name: 30 Year US Government Bond
  asset_class: government bond
  curcdd: USD
  ric: US
ZT:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-2 YEAR US T-NOTE COMP. CONTINUOUS
  name: 2 Year US Government Note
  asset_class: government bond
  curcdd: USD
  ric: TU
ZF:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-5 YEAR US T-NOTE COMP. CONT.
  name: 5 Year US Government Note
  asset_class: government bond
  curcdd: USD
  ric: FV
ZN:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-10 YRS US T-NOTE COMP. CONTINUOUS
  name: 10 Year US Government Note
  asset_class: government bond
  curcdd: USD
  ric: TY
FGBS:
  exchange_name: EUREX
  calcseriesname: EUREX-EURO SCHATZ CONTINUOUS
  name: Euro Schatz (2-Year German Federal Bond)
  asset_class: government bond
  curcdd: EUR
  ric: FGBS
FGBM:
  exchange_name: EUREX
  calcseriesname: EUREX-EURO BOBL CONTINUOUS
  name: Euro Bobl (5-Year German Federal Bond)
  asset_class: government bond
  curcdd: EUR
  ric: FGBM
FGBL:
  exchange_name: EUREX
  calcseriesname: EUREX-EURO BUND CONTINUOUS
  name: Euro Bund (10-Year German Federal Bond)
  asset_class: government bond
  curcdd: EUR
  ric: FGBL
FGBX:
  exchange_name: EUREX
  calcseriesname: EUREX-EURO BUXL CONTINUOUS
  name: Euro Buxl (30-Year German Federal Bond)
  asset_class: government bond
  curcdd: EUR
  ric: FGBX
FOAT:
  exchange_name: EUREX
  calcseriesname: EUREX-LONG EURO OAT CONTINUOUS
  name: French OAT (10-Year Government Bond)
  asset_class: government bond
  curcdd: EUR
  ric: FOAT
FBTP:
  exchange_name: EUREX
  calcseriesname: EUREX-EURO BTP CONTINUOUS
  name: Italian BTP (10-Year Government Bond)
  asset_class: government bond
  curcdd: EUR
  ric: FBTP
CONF:
  exchange_name: EUREX
  calcseriesname: EUREX-SWISS CONF CONTINUOUS
  name: Swiss Confederation Bond (~10-Year benchmark)
  asset_class: government bond
  curcdd: CHF
  ric: CONF
R:
  exchange_name: Euronext.LIFFE London
  calcseriesname: LIFFE-LONG GILT CONTINUOUS
  name: UK Long Gilt (~10-Year benchmark)
  asset_class: government bond
  curcdd: GBP
  ric: FLG
CGB:
  exchange_name: Montreal Exchange
  calcseriesname: ME-10Y CANADIAN GOVT BOND CONTINUOUS
  name: 10 Year Canadian Government Bond
  asset_class: government bond
  curcdd: CAD
  ric: CGB
"160120001":
  exchange_name: Osaka Exchange
  calcseriesname: TSE-10 YEAR T-BOND CONTINUOUS
  name: 10 Year Japanese Government Bond
  asset_class: government bond
  curcdd: JPY
  ric: JGB
YT:
  exchange_name: Sydney Futures Exchange
  calcseriesname: SFE-AUST 3 YEAR T-BOND CONT.
  name: 3 Year Australian Government Bond
  asset_class: government bond
  curcdd: AUD
  ric: YTT
XT:
  exchange_name: Sydney Futures Exchange
  calcseriesname: SFE-AUST 10 YEAR T-BOND CONT.
  name: 10 Year Australian Government Bond
  asset_class: government bond
  curcdd: AUD
  ric: YTC
### CURRENCY FUTURES ###
6A:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-AUSTRALIAN DOLLR COMP. CONTINUOUS
  name: Australian Dollar
  asset_class: currency
  curcdd: USD
  ric: AD
6B:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-STERLING COMP. CONTINUOUS
  name: Sterling
  asset_class: currency
  curcdd: USD
  libor: L
  ric: BP
6C:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-CANADIAN DOLLAR COMP. CONTINUOUS
  name: Canadian Dollar
  asset_class: currency
  curcdd: USD
  ric: CD
6E:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-EURO COMP. CONTINUOUS
  name: Euro
  asset_class: currency
  curcdd: USD
  ric: URO
6J:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-JAPANESE YEN COMP. CONTINUOUS
  name: Japanese Yen
  asset_class: currency
  curcdd: USD
  ric: JY
6N:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-NEW ZEALAND $ COMP. CONTINUOUS
  name: New Zealand Dollar
  asset_class: currency
  curcdd: USD
  ric: NE
6S:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-SWISS FRANC COMP. CONTINUOUS
  name: Swiss Franc
  asset_class: currency
  curcdd: USD
  ric: SF
NOK:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-NORWEGIAN KRONE CONTINUOUS
  name: Norwegian Krone
  asset_class: currency
  curcdd: USD
  ric: NOKA
SEK:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-SWEDISH KRONA CONTINUOUS
  name: Swedish Krona
  asset_class: currency
  curcdd: USD
  ric: SEKA
### EQUITY MARKET INDEX FUTURES ###
ES:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-MINI S&P 500 INDEX CONT.
  name: S&P 500 Index
  asset_class: equity index
  curcdd: USD
  ric: ES
NQ:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-E MINI NASDAQ 100 CONTINUOUS
  name: Nasdaq 100 Index
  asset_class: equity index
  curcdd: USD
  ric: NQ
RTY:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-E-MINI RUSSELL 2000 C CONT
  name: Russell 2000 Index
  asset_class: equity index
  curcdd: USD
  ric: RTY
EMD:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-EMINI S&P 400 MIDCAP CONTINUOU
  name: S&P 400 Midcap Index
  asset_class: equity index
  curcdd: USD
  ric: DM
YM:
  exchange_name: Chicago Board of Trade (CBOT)
  calcseriesname: CBT-MINI DOW JONES CONTINUOUS
  name: Dow Jones Industrial Index
  asset_class: equity index
  curcdd: USD
  ric: YM
AP:
  exchange_name: Sydney Futures Exchange
  calcseriesname: SFE-SPI 200 INDEX CONT. TRAD
  name: SPI 200 Index (Australia)
  asset_class: equity index
  curcdd: AUD
  ric: YAP
Z:
  exchange_name: Euronext.LIFFE London
  calcseriesname: LIFFE-FTSE 100 INDEX CONTINUOUS
  name: FTSE 100 Index
  asset_class: equity index
  curcdd: GBP
  ric: FFI
SXF:
  exchange_name: Montreal Stock Exchange
  calcseriesname: ME-S&P CANADA 60 INDEX CONT.
  name: S&P TSX Canada 60 Index
  asset_class: equity index
  curcdd: CAD
  ric: SXF
FESX:
  exchange_name: EUREX
  calcseriesname: EUREX-EURO STOXX 50 CONTINUOUS
  name: Euro Stoxx 50 Index
  asset_class: equity index
  curcdd: EUR
  ric: STXE
FCE:
  exchange_name: Euronext Paris
  calcseriesname: MONEP-CAC 40 INDEX CONTINUOUS
  name: CAC 40 Index (France)
  asset_class: equity index
  curcdd: EUR
  ric: FCE
FDAX:
  exchange_name: EUREX
  calcseriesname: EUREX-DAX INDEX CONTINUOUS
  name: DAX 40 Index (Germany)
  asset_class: equity index
  curcdd: EUR
  ric: FDX
FIE:
  exchange_name: MEFF Renta Variable
  calcseriesname: MEFF-IBEX 35 PLUS INDEX CONT.
  name: IBEX 35 Plus Index (Spain)
  asset_class: equity index
  curcdd: EUR
  ric: MFXI
FIB:
  exchange_name: Italian Derivatives Market
  calcseriesname: IDEM-FTSE MIB CONTINUOUS
  name: FTSE MIB Index (Italy)
  asset_class: equity index
  curcdd: EUR
  ric: IFS
HSI:
  exchange_name: Hong Kong Futures Exchange
  calcseriesname: HKFE-HANG SENG INDEX CONTINUOUS
  name: Hang Seng Index (China / Hong Kong)
  asset_class: equity index
  curcdd: HKD
  ric: HSI
"160120006":
  exchange_name: Osaka Exchange
  calcseriesname: TSE-MINI-TOPIX CONTINUOUS
  name: TOPIX Index (Japan)
  asset_class: equity index
  curcdd: JPY
  ric: JNI
"164120019":
  exchange_name: Osaka Exchange
  calcseriesname: OSX-NIKKEI 225 INDEX CONTINUOUS
  name: Nikkei 225 Index (Japan)
  asset_class: equity index
  curcdd: JPY
  ric: JNI
FTI:
  exchange_name: Euronext Amsterdam
  calcseriesname: AEX-AEX INDEX CONTINUOUS
  name: AEX Index (Netherlands)
  asset_class: equity index
  curcdd: EUR
  ric: AEX
FXS30:
  exchange_name: OM Nordic Exchange
  calcseriesname: OMX-OMXS30 INDEX CONTINUOUS
  name: OMXS30 (Sweden) Index
  asset_class: equity index
  curcdd: SEK
  ric: OMXS30
FSMI:
  exchange_name: EUREX
  calcseriesname: EUREX-SMI CONT.TRADITIONAL
  name: Swiss Market Index
  asset_class: equity index
  curcdd: CHF
  ric: FSMI
FATX:
  exchange_name: EUREX
  calcseriesname: EUREX-ATX INDEX CONT
  name: Austrian ATX Index
  asset_class: equity index
  curcdd: EUR
  ric: FATXA
SGP:
  exchange_name: Singapore Exchange - Derivatives Trading Division
  calcseriesname: SGX DT-MSCI SING. INDEX CONT. TRAD
  name: MSCI Singapore Index
  asset_class: equity index
  curcdd: SGD
  ric: SSG
A01:
  exchange_name: Korea Stock Exchange
  calcseriesname: KSE-KOSPI 200 INDEX CONTINUOUS
  name: Kospi 200 Index (South Korea)
  asset_class: equity index
  curcdd: KRW
  ric: KS
### VOLATILITY FUTURES ###
VX:
  exchange_name: CBOE Futures Exchange
  calcseriesname: CFE-VIX INDEX CONT. TRAD
  name: VIX Index
  asset_class: volatility
  curcdd: USD
  ric: VX
FVS:
  exchange_name: EUREX
  calcseriesname: EUREX-MINI VSTOXX CONTINUOUS
  name: VSTOXX Index
  asset_class: volatility
  curcdd: EUR
  ric: FVS
### SHORT TERM INTEREST RATE FUTURES ###
SR3:
  exchange_name: Chicago Mercantile Exchange (CME)
  calcseriesname: CME-3 MONTH SOFR CONT
  name: 3-Month SOFR (replaces 3-Month USD LIBOR / Eurodollar, pre-2018)
  asset_class: short-term interest rate
  curcdd: USD
  ric: SRA
I:
  exchange_name: Euronext.LIFFE London
  calcseriesname: LIFFE-3 MTH EURIBOR CONT.TRADITIONAL
  name: 3-Month EURIBOR
  asset_class: short-term interest rate
  curcdd: EUR
  ric: FEI
"91":
  exchange_name: Osaka Exchange
  calcseriesname: OSX-3-MONTH TONA CONT
  name: 3-Month TONA (replaces Euroyen / 3-Month JPY LIBOR / TIBOR, pre-2023)
  asset_class: short-term interest rate
  curcdd: JPY
  ric: JTOA
SO3:
  exchange_name: Euronext.LIFFE London
  calcseriesname: LIFFE-3MTH STERLING CONT.TRADITIONAL
  name: 3-Month SONIA (replaces Short Sterling / 3-Month GBP LIBOR, pre-2018)
  asset_class: short-term interest rate
  curcdd: GBP
  ric: SON3
IR:
  exchange_name: Sydney Futures Exchange
  calcseriesname: SFE-AUST 90 DAY BANK BILLS CONT.
  name: 90-Day Australian Bank Bill
  asset_class: short-term interest rate
  curcdd: AUD
  ric: YBA
BB:
  exchange_name: Sydney Futures Exchange
  calcseriesname: NZFE-90 DAY BANK BILLS CONT.
  name: 90-Day New Zealand Bank Bill
  asset_class: short-term interest rate
  curcdd: NZD
  ric: NBB
SA3:
  exchange_name: Intercontinental Exchange - ICE Futures Limited
  calcseriesname: ICE-3MTH SARBON CONT
  name: 3-Month SARON (replaces 3-Month CHF LIBOR, pre-2021)
  asset_class: short-term interest rate
  curcdd: CHF
  ric: SARO3
